apiVersion: apps/v1
kind: Deployment
metadata:

  name: rest-api-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rest-api
  template:
    metadata:
      labels:
        app: rest-api
    spec:
      containers:
      - name: rest-api
        image: rest-api:latest
        ports:
        - containerPort: 3000
