apiVersion: v1
kind: Service
metadata:
  name: rest-api-service
  namespace: default
spec:
  selector:
    app: rest-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
